### ISSUE TITLE
How to get the target temp for a zone ?

### ISSUE THREAD

**Issue by vw-kombi** [Swamp-Ig/homeassistant_izone#58]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I want to get the trage temp from a zone - I am able to get the current temp,m but what is the setting for traget temp ?  As below current temp works, but target temp is always unknown.  I assume it is a different variable but i dont understand the code as i sam not a dev.

      - name: "Cameron Temperature"
        unique_id: "Cameron Temperature"
        unit_of_measurement: "°C"
        icon: mdi:thermometer
        state: "{{ state_attr('climate.cameron','current_temperature') }}"
      - name: "Cameron Target Temperature"
        unique_id: "Cameron Target Temperature"
        unit_of_measurement: "°C"
        icon: mdi:thermometer
        state: "{{ state_attr('climate.cameron','target_temperature') }}"

### Describe the solution you'd like

I would make a sensor for each zone's target temp.
I can then compare it with each zones current temp and do automations based on both.

### Describe alternatives you've considered

I have looked at the code - bit i m not good enough to understand it......

### Additional context

This works - state: "{{ state_attr('climate.cameron','current_temperature') }}"
This does not - state: "{{ state_attr('climate.cameron','target_temperature') }}"

**Comment by vw-kombi** [comment]
OK - I have done some 'learning' and found I can interigate the things in HA - sorry, I am new at this.  I found this and it seems the value temerature should be used - I added that to the yaml, restarted and any status of heat_cool has a value -  :


![image](https://github.com/Swamp-Ig/homeassistant_izone/assets/56822460/03f0280e-1eee-486a-80eb-3098416cef29)

**Comment by Swamp-Ig** [comment]
Looks all sorted :)
